plane:
  CGx: 0.15
  CGz: 0.0
  attack_angle: 3.565536966325324
  body_len: 0.3
  body_span: 0.1
  cannard: true
  cannard_airfoil: naca0010
  cannard_attack_angle: 4.802120892739734
  cannard_chord: 0.06709695226710286
  cannard_len: 0.15
  cannard_start: 0.06882065381656773
  cannard_thickness: 0.015
  cannard_z_offset: 0.015
  dihedral: 0
  leading_edge_length: 0.4
  sweep: 37.02072930472494
  taper_ratio: 0.40961668391074263
  washout: -3.0745773527772196
  wing_airfoil_base: s1223
  wing_airfoil_tip: naca0010
  wing_base_start: 0.38828337916913747
  wing_chord: 0.11683765151756685
  wing_lift: 0
  wing_min_thickness: 0.015
  winglet_airfoil: naca0010
  winglet_angle: 77.14307512200791
  winglet_leading_edge_len: 0.04922028091382641
  winglet_radius: 0.012697910451479152
  winglet_sections: 1
  winglet_sweep: 48.20711368578464
  winglet_taper_ratio: 0.3744283066661165
  winglet_toe: 7.993993797285568


airfoils:
  - 'mh60'
  - 'naca0012'
  - 'naca0010'
  - 'naca0008'
  - 'mh45'
  - 'naca2412'
  - 'naca4412'
  - 'naca4415'
  - 'naca6412'
  - 'clarky'
  - 'ag04'
  - 'sd7032'
  - 's1223'
  - 'naca23012'

constraints:
  attack_angle:
    - 0
    - 8
  body_span: 0.1
  body_len: 0.3
  wing_base_start:
   - 0.2
   - 0.7
  wing_chord:
   - 0.1
   - 0.2
  wing_lift: 0
  leading_edge_length: 0.4
  sweep:
   - 0
   - 60
  taper_ratio:
   - 0.3
   - 1
  washout:
   - -10
   - 10
  dihedral: 0
  winglet_sweep:
   - 0
   - 60
  winglet_toe:
    - 0
    - 30
  winglet_angle:
   - 20
   - 90
  winglet_sections: 1  # ,affects calculation accuracy and speed
  winglet_radius:
    - 0.01
    - 0.02
  winglet_taper_ratio:
    - 0.3
    - 1
  winglet_leading_edge_len:
   - 0.01
   - 0.05
  CGx: 0.15
  CGz: 0.
  cannard: True
  cannard_attack_angle:
    - -2
    - 8
  cannard_start:
    - 0.05
    - 0.07
  cannard_chord:
    - 0.03
    - 0.07
  cannard_len: 0.15
  cannard_z_offset: 0.015
  cannard_thickness: 0.015
  wing_min_thickness: 0.015
  

data:
  output_path: 'results'

optimization:
  method: 'both'
  particles_ab: 400
  particles_vlm: 30

targets:
  # NO: 100
  Cma: -0.1
  Cla: 4
  Clp: -0.6
  Cmq: -12
  Cnb: 0.1
  Clb: -0.1
  Cnr: -0.1
  CLCD: 25

target_range:
  - 0
  - 5

