plane:
  CGx: 0.35
  CGz: -0.07
  attack_angle: 8.0
  body_height: 0.07
  body_len: adaptive
  body_span: 0.12
  cannard: false
  cannard_airfoil: naca0010
  cannard_attack_angle: 1.27710382
  cannard_chord: 0.0504440033
  cannard_len: 0.15
  cannard_start: 0.06120297
  cannard_thickness: 0.015
  cannard_z_offset: 0.015
  dihedral: -1.9416223
  foot: false
  foot_airfoil: naca0012
  foot_base_start: 0.0
  foot_chord: 0.06
  foot_taper: 0.5
  foot_thickness: 0.01
  leading_edge_length: 0.45
  sweep: 33.3365381
  taper_ratio: 0.532064975
  washout: -4.66531235
  wing_airfoil_base: mh60
  wing_airfoil_tip: mh60
  wing_base_start: 0.274121545
  wing_chord: 0.197491163
  wing_lift: 0
  wing_min_thickness: 0.015
  winglet_airfoil: naca2412
  winglet_angle: -90.0
  winglet_leading_edge_len: 0.01
  winglet_radius: 0.019123632
  winglet_sections: 1
  winglet_sweep: 19.3512049
  winglet_taper_ratio: 0.684901758
  winglet_toe: 1.60852531
  winglets: true
airfoils:
  - 'mh60'
  - 'naca0012'
  - 'naca0010'
  - 'naca0008'
  - 'mh45'
  - 'naca2412'
  - 'naca4412'
  - 'naca4415'
  - 'naca6412'
  - 'clarky'
  - 'ag04'
  - 'sd7032'
  - 's1223'
  - 'naca23012'

constraints:
  attack_angle:
    - 0
    - 8
  body_span:
   - 0.05
   - 0.5
  body_height:
   - 0.01
   - 0.2
  body_len:
   - 0.05
   - 1
  wing_base_start:
   - 0.15
   - 0.5
  wing_chord:
   - 0.17
   - 0.2
  wing_lift:
   - -0.5
   - 0.5
  wing_min_thickness:
   - 0.01
   - 0.05
  leading_edge_length:
   - 0.1
   - 0.55
  sweep:
   - 15
   - 45
  taper_ratio:
   - 0.3
   - 0.7
  washout:
   - -5
   - 5
  dihedral:
   - -5
   - 5
  winglets: true
  winglet_sweep:
   - 0
   - 60
  winglet_toe:
    - 0
    - 5
  winglet_angle:
   - -90
   - 90
  winglet_sections:
   - 1
   - 5
  winglet_radius:
    - 0.01
    - 0.02
  winglet_taper_ratio:
    - 0.3
    - 1
  winglet_leading_edge_len:
   - 0.01
   - 0.05
  CGx:
   - 0.15
   - 0.5
  CGz:
   - -0.80
   - 0.80
  cannard: false
  cannard_attack_angle:
    - 0
    - 5
  cannard_start:
    - 0.05
    - 0.07
  cannard_chord:
    - 0.03
    - 0.07
  cannard_len:
   - 0.
   - 0.3
  cannard_z_offset:
   - 0.
   - 1.
  cannard_thickness:
   - 0.01
   - 0.05
  foot: true
  foot_base_start:
   - 0.
   - 0.9
  foot_taper:
   - -1.
   - 1.
  foot_chord:
   - 0.01
   - 0.20
  foot_thickness:
   - 0.005
   - 0.03
  

data:
  output_path: 'results'

optimization:
  method: 'both'
  particles_ab: 400
  particles_ll: 100
  particles_vlm: 50
  start_with_plane: True
  to_optimize:
    - 'attack_angle'
    - 'wing_base_start'
    - 'wing_chord'
    - 'sweep'
    - 'taper_ratio'
    - 'washout'
    - 'dihedral'
    - 'winglet_sweep'
    - 'winglet_toe'
    - 'winglet_angle'
    - 'winglet_taper_ratio'
    - 'winglet_leading_edge_len'
    - 'wing_airfoil_base'
    - 'wing_airfoil_tip'
    - 'winglet_airfoil'
    - 'CGx'
    - 'CGz'

targets:
  # NO: 100
  CL: 0.8
  Cma: -0.5
  Clp: -0.6
  Cmq: -4
  Cnb: 0.1
  Clb: -0.1
  Cnr: -0.1
  CLCD: 25

target_range:
  - 1
  - 3


velocity: 15

alphas:
 - -5
 - -4
 - -3
 - -2
 - -1
 - 0
 - 1
 - 2
 - 3
 - 4
 - 5
 - 7
 - 10
