plane:
  CGx: 0.25
  CGz: 0.0
  attack_angle: 5.048786821433829
  body_len: 0.3
  body_span: 0.1
  cannard: true
  cannard_airfoil: mh45
  cannard_attack_angle: 1.732703639966592
  cannard_chord: 0.04737554922778689
  cannard_len: 0.15
  cannard_start: 0.06971742027279011
  cannard_thickness: 0.015
  cannard_z_offset: 0.015
  dihedral: -2.283618832897457
  leading_edge_length: 0.4
  sweep: 9.167166047788557
  taper_ratio: 0.7523916039290168
  washout: 3.2478340855283294
  wing_airfoil_base: naca4415
  wing_airfoil_tip: mh45
  wing_base_start: 0.4291716749676211
  wing_chord: 0.11120040734406886
  wing_lift: 0
  wing_min_thickness: 0.015
  winglet_airfoil: naca0010
  winglet_angle: 68.93130768403267
  winglet_leading_edge_len: 0.018840077819295607
  winglet_radius: 0.012330449743653856
  winglet_sections: 1
  winglet_sweep: 29.46438898391796
  winglet_taper_ratio: 0.866063927665728
  winglet_toe: 14.198877964201607


airfoils:
  - 'mh60'
  - 'naca0012'
  - 'naca0010'
  - 'naca0008'
  - 'mh45'
  - 'naca2412'
  - 'naca4412'
  - 'naca4415'
  - 'naca6412'
  - 'clarky'
  - 'ag04'
  - 'sd7032'
  - 's1223'
  - 'naca23012'

constraints:
  attack_angle:
    - 0
    - 8
  body_span: 0.07
  body_len: 'adaptive'
  wing_base_start:
   - 0.2
   - 0.5
  wing_chord:
   - 0.1
   - 0.2
  wing_lift: 0
  leading_edge_length: 0.4
  sweep:
   - 15
   - 45
  taper_ratio:
   - 0.3
   - 0.7
  washout:
   - -5
   - 5
  dihedral:
   - -5
   - 5
  winglet_sweep:
   - 0
   - 60
  winglet_toe:
    - 0
    - 5
  winglet_angle:
   - 20
   - 90
  winglet_sections: 1  # ,affects calculation accuracy and speed
  winglet_radius:
    - 0.01
    - 0.02
  winglet_taper_ratio:
    - 0.3
    - 1
  winglet_leading_edge_len:
   - 0.01
   - 0.05
  CGx: 0.25  # percent body + wings (0.25 - 25% from the front)
  CGz: 0.
  cannard: True
  cannard_attack_angle:
    - 0
    - 5
  cannard_start:
    - 0.05
    - 0.07
  cannard_chord:
    - 0.03
    - 0.07
  cannard_len: 0.15
  cannard_z_offset: 0.015
  cannard_thickness: 0.015
  wing_min_thickness: 0.015
  

data:
  output_path: 'results'

optimization:
  method: 'both'
  particles_ab: 400
  particles_vlm: 50

targets:
  # NO: 100
  Cma: -0.1
  Clp: -0.6
  Cmq: -6
  Cnb: 0.1
  Clb: -0.1
  Cnr: -0.1
  CLCD: 25

target_range:
  - 1
  - 3


velocity: 15

