plane:
  wing_airfoil_base: 'mh60'
  wing_airfoil_tip: 'naca0008'
  winglet_airfoil: 'mh45'
  wing_min_thickness: 0.015
  attack_angle: 2  # deg
  body_span: 0.1  # m
  body_len: 0.3  # m
  wing_base_start: 0.33  # % from body_len
  wing_chord: 0.18  # m
  wing_lift: 0  # m, from body midpoint
  leading_edge_length: 0.4  # m
  sweep: 20  # deg
  taper_ratio: 0.5
  washout: 1  # deg
  dihedral: 0  # deg, keep at 0 for easier construction
  winglet_sweep: 60  # deg
  winglet_toe: 0  # deg
  winglet_angle: 20  # deg
  winglet_sections: 2  # ,affects calculation accuracy and speed
  winglet_radius: 0.02  # m
  winglet_taper_ratio: 0.5
  winglet_leading_edge_len: 0.05  # m
  CGx: 0.1
  CGz: 0.
  cannard: True
  cannard_attack_angle: 2  # deg
  cannard_airfoil: 'mh60'
  cannard_start: 0.1
  cannard_chord: 0.05
  cannard_len: 0.15
  cannard_z_offset: 0.02
  cannard_thickness: 0.02

airfoils:
  - 'mh60'
  - 'naca0012'
  - 'naca0010'
  - 'naca0008'
  - 'mh45'
  - 'naca2412'
  - 'naca4412'
  - 'naca4415'
  - 'naca6412'
  - 'clarky'
  - 'ag04'
  - 'sd7032'
  - 's1223'
  - 'naca23012'

constraints:
  attack_angle:
    - 0
    - 8
  body_span: 0.1
  body_len: 0.3
  wing_base_start:
   - 0.2
   - 0.7
  wing_chord:
   - 0.1
   - 0.2
  wing_lift: 0
  leading_edge_length: 0.4
  sweep:
   - 0
   - 60
  taper_ratio:
   - 0.3
   - 1
  washout:
   - -10
   - 10
  dihedral: 0
  winglet_sweep:
   - 0
   - 60
  winglet_toe:
    - 0
    - 30
  winglet_angle:
   - 20
   - 90
  winglet_sections: 1  # ,affects calculation accuracy and speed
  winglet_radius:
    - 0.01
    - 0.02
  winglet_taper_ratio:
    - 0.3
    - 1
  winglet_leading_edge_len:
   - 0.01
   - 0.05
  CGx: 0.15
  CGz: 0.
  cannard: True
  cannard_attack_angle:
    - -2
    - 8
  cannard_start:
    - 0.05
    - 0.07
  cannard_chord:
    - 0.03
    - 0.07
  cannard_len: 0.15
  cannard_z_offset: 0.015
  cannard_thickness: 0.015
  wing_min_thickness: 0.015
  

data:
  output_path: 'results'

optimization:
  method: 'both'
  particles_ab: 250
  particles_vlm: 30

targets:
  # NO: 100
  Cma: -0.1
  Cla: 4
  Clp: -0.6
  Cmq: -12
  Cnb: 0.1
  Clb: -0.1
  Cnr: -0.1
  CLCD: 25

target_range:
  - 0
  - 5

