plane:
  CGx: 0.35
  CGz: 0.07
  attack_angle: 7.742481447325077
  body_len: adaptive
  body_span: 0.12
  body_height: 0.15
  cannard: true
  cannard_airfoil: naca2412
  cannard_attack_angle: 0.05040988942586061
  cannard_chord: 0.04822547950963443
  cannard_len: 0.15
  cannard_start: 0.06700496460455721
  cannard_thickness: 0.015
  cannard_z_offset: 0.015
  dihedral: -4.430958758512813
  leading_edge_length: 0.45
  sweep: 30.010112252461386
  taper_ratio: 0.41537267878228684
  washout: -4.031818423583446
  wing_airfoil_base: mh60
  wing_airfoil_tip: naca0008
  wing_base_start: 0.2
  wing_chord: 0.17153770612414998
  wing_lift: 0
  wing_min_thickness: 0.015
  winglet_airfoil: naca4412
  winglet_angle: 90.0
  winglet_leading_edge_len: 0.024943346204019976
  winglet_radius: 0.019266241586323302
  winglet_sections: 1
  winglet_sweep: 44.02728759978745
  winglet_taper_ratio: 0.7775881883966108
  winglet_toe: 1.2989734336000254

airfoils:
  - 'mh60'
  - 'naca0012'
  - 'naca0010'
  - 'naca0008'
  - 'mh45'
  - 'naca2412'
  - 'naca4412'
  - 'naca4415'
  - 'naca6412'
  - 'clarky'
  - 'ag04'
  - 'sd7032'
  - 's1223'
  - 'naca23012'

constraints:
  attack_angle:
    - 0
    - 8
  body_span: 0.07
  body_len: 'adaptive'
  wing_base_start:
   - 0.2
   - 0.5
  wing_chord:
   - 0.1
   - 0.2
  wing_lift: 0
  leading_edge_length: 0.4
  sweep:
   - 15
   - 45
  taper_ratio:
   - 0.3
   - 0.7
  washout:
   - -5
   - 5
  dihedral:
   - -5
   - 5
  winglet_sweep:
   - 0
   - 60
  winglet_toe:
    - 0
    - 5
  winglet_angle:
   - 20
   - 90
  winglet_sections: 1  # ,affects calculation accuracy and speed
  winglet_radius:
    - 0.01
    - 0.02
  winglet_taper_ratio:
    - 0.3
    - 1
  winglet_leading_edge_len:
   - 0.01
   - 0.05
  CGx:
   - 0.15
   - 0.5
  CGz: 0.
  cannard: True
  cannard_attack_angle:
    - 0
    - 5
  cannard_start:
    - 0.05
    - 0.07
  cannard_chord:
    - 0.03
    - 0.07
  cannard_len: 0.15
  cannard_z_offset: 0.015
  cannard_thickness: 0.015
  wing_min_thickness: 0.015
  

data:
  output_path: 'results'

optimization:
  method: 'both'
  particles_ab: 400
  particles_vlm: 50
  start_with_plane: True

targets:
  # NO: 100
  Cma: -0.5
  Clp: -0.6
  Cmq: -4
  Cnb: 0.1
  Clb: -0.1
  Cnr: -0.1
  CLCD: 25

target_range:
  - 1
  - 3


velocity: 15

alphas:
 - -5
 - -4
 - -3
 - -2
 - -1
 - 0
 - 1
 - 2
 - 3
 - 4
 - 5
 - 7
 - 10
