[project]
name = "wingdesign"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aerosandbox>=4.2.9",
    "matplotlib>=3.10.8",
    "pyqt5>=5.15.11",
]
